videos:
- content_question_de: Was ist die Distanz, die als letztes zu sehen war?
  content_question_en: What is the distance that was last visible?
  description_de: ''
  description_en: ''
  duration: 176
  name_de: 97 Percent
  name_en: 97 Percent
  src_id: 97Percent
- content_question_de: Wie viele "Assassins" gibt es?
  content_question_en: How many assassins are there?
  description_de: ''
  description_en: ''
  duration: 191
  name_de: Assassins Creed
  name_en: Assassins Creed
  src_id: AssassinsCreed
- content_question_de: Wie viele Urlauber sind in dem Video zu sehen?
  content_question_en: How many people are taking vacation in this video?
  description_de: ''
  description_en: ''
  duration: 164
  name_de: Bali Road Trip
  name_en: Bali Road Trip
  src_id: BaliRoadTrip
- content_question_de: Welche Farbe hat das Flugzeug?
  content_question_en: What color does the airplane have?
  description_de: ''
  description_en: ''
  duration: 161
  name_de: Barefoot
  name_en: Barefoot
  src_id: Barefoot
- content_question_de: Wie viele kleinen "Gegner" hat Big Buck Bunny?
  content_question_en: How many "enemies" does Big Buck Bunny have?
  description_de: ''
  description_en: ''
  duration: 200
  name_de: Big Buck Bunny
  name_en: Big Buck Bunny
  src_id: BigBuckBunny
- content_question_de: Auf welchem Plastiktier ist die eine Frau zu sehen?
  content_question_en: Which plastic animal does the woman ride on?
  description_de: ''
  description_en: ''
  duration: 145
  name_de: Cliff
  name_en: Cliff
  src_id: Cliff
- content_question_de: Welche Farbe hat das Hemd des Jungen?
  content_question_en: What color does the boy's shirt have?
  description_de: ''
  description_en: ''
  duration: 67
  name_de: Coffee Virgin
  name_en: Coffee Virgin
  src_id: CoffeeVirgin
- content_question_de: Sieht man Leute Skifahren oder Snowboarden?
  content_question_en: Do you see people skiing or snowboarding?
  description_de: ''
  description_en: ''
  duration: 196
  name_de: Dubai
  name_en: Dubai
  src_id: Dubai
- content_question_de: Welches Team ist zu sehen?
  content_question_en: Which team to you see?
  description_de: ''
  description_en: ''
  duration: 172
  name_de: Football4k
  name_en: Football4k
  src_id: Football4k
- content_question_de: Welches Muster hat der Ball?
  content_question_en: What's the pattern of the ball?
  description_de: ''
  description_en: ''
  duration: 95
  name_de: Football Pro
  name_en: Football Pro
  src_id: FootballPro
- content_question_de: Waren auf dem Eisberg Pinguine?
  content_question_en: Were there any penguins on the iceberg?
  description_de: ''
  description_en: ''
  duration: 156
  name_de: Go Pro Hero 1
  name_en: Go Pro Hero 1
  src_id: GoProHero4k
- content_question_de: Stürzt einer der Surfer?
  content_question_en: Does one of the survers fall?
  description_de: ''
  description_en: ''
  duration: 59
  name_de: Go Pro Hero 2
  name_en: Go Pro Hero 2
  src_id: GoproHero
- content_question_de: Wie heißt der Modelmaker, der am Anfang erwähnt wird?
  content_question_en: What's the model maker's name mentioned at the beginning?
  description_de: ''
  description_en: ''
  duration: 177
  name_de: Holorama
  name_en: Holorama
  src_id: Holorama
- content_question_de: Von wem ist der Film?
  content_question_en: Who made this movie?
  description_de: ''
  description_en: ''
  duration: 147
  name_de: Hoverboard
  name_en: Hoverboard
  src_id: Hoverboard
- content_question_de: Wie viele Augen haben die Planetenbewohner?
  content_question_en: How many eyes do the planet's inhabitants have?
  description_de: ''
  description_en: ''
  duration: 158
  name_de: Johnny Express
  name_en: Johnny Express
  src_id: JohnnyExpress
- content_question_de: Welchen Sport spielen die Kinder im Dorf?
  content_question_en: Which game are the children playing in the village?
  description_de: ''
  description_en: ''
  duration: 144
  name_de: Machu Picchu
  name_en: Machu Picchu
  src_id: MachuPicchu
- content_question_de: In welchem Tierkostüm steckt die Frau?
  content_question_en: Which animal suit is the woman wearing?
  description_de: ''
  description_en: ''
  duration: 115
  name_de: Nespresso
  name_en: Nespresso
  src_id: Nespresso
- content_question_de: Hat die Nonne eine Brille?
  content_question_en: Does the nun wear glasses?
  description_de: ''
  description_en: ''
  duration: 145
  name_de: None Of That
  name_en: None Of That
  src_id: NoneOfThat
- content_question_de: Gab es irgendwelche Sportarten, die gezeigt wurden?
  content_question_en: Were any sports activities shown?
  description_de: ''
  description_en: ''
  duration: 127
  name_de: Orthopaedics
  name_en: Orthopaedics
  src_id: Orthopaedics
- content_question_de: Wo spielen die Szenen?
  content_question_en: Where do the scenes play?
  description_de: ''
  description_en: ''
  duration: 132
  name_de: Real GTA
  name_en: Real GTA
  src_id: RealGTA
- content_question_de: Was ist der Name des Drachen?
  content_question_en: What's the dragon's name?
  description_de: ''
  description_en: ''
  duration: 147
  name_de: Sintel
  name_en: Sintel
  src_id: Sintel
- content_question_de: Wo spielt die Szene?
  content_question_en: Where does the scene play?
  description_de: ''
  description_en: ''
  duration: 119
  name_de: State Zero
  name_en: State Zero
  src_id: StateZero
- content_question_de: Zu welchem Staat gehört die Insel St. John?
  content_question_en: Which country does St. John belong to?
  description_de: ''
  description_en: ''
  duration: 149
  name_de: St John
  name_en: St John
  src_id: StJohn
- content_question_de: Welcher Star Wars Film war gemeint?
  content_question_en: Which Star Wars movie is this referring to?
  description_de: ''
  description_en: ''
  duration: 109
  name_de: Star Wars Toys
  name_en: Star Wars Toys
  src_id: StarWarsToys
- content_question_de: Wer unterbricht die Storm Trooper am Ende?
  content_question_en: Who is interrupting the storm troopers at the end?
  description_de: ''
  description_en: ''
  duration: 111
  name_de: Storm Troopers
  name_en: Storm Troopers
  src_id: StormTroopers
- content_question_de: Welche Farbe hat die Jacke des Manns mit dem Roboter-Auge?
  content_question_en: What is the color of the jacket of the man who is wearing the
    cyborg eye?
  description_de: ''
  description_en: ''
  duration: 174
  name_de: Tears Of Steel
  name_en: Tears Of Steel
  src_id: TearsOfSteel
- content_question_de: Wieviele Flugzeuge sind zu sehen?
  content_question_en: How many airplanes are visible?
  description_de: ''
  description_en: ''
  duration: 153
  name_de: The Ocean Maker
  name_en: The Ocean Maker
  src_id: TheOceanMaker
- content_question_de: Tragen beide Protagonisten einen Bart?
  content_question_en: Do both protagonists wear a beard?
  description_de: ''
  description_en: ''
  duration: 165
  name_de: The Ramens
  name_en: The Ramens
  src_id: TheRamens
- content_question_de: Platzt einer der Luftballons?
  content_question_en: Does one of the balloons pop?
  description_de: ''
  description_en: ''
  duration: 168
  name_de: Tumbleweed Tango
  name_en: Tumbleweed Tango
  src_id: TumbleweedTango
- content_question_de: Wo spielt die Szene?
  content_question_en: Where does the scene play?
  description_de: ''
  description_en: ''
  duration: 175
  name_de: Watch Dogs Parkour
  name_en: Watch Dogs Parkour
  src_id: WatchDogsParkour
- content_question_de: Wie heißen die Brüder?
  content_question_en: How are the brothers called?
  description_de: ''
  description_en: ''
  duration: 178
  name_de: Water Makers
  name_en: Water Makers
  src_id: WaterMakers
- content_question_de: Wonach sucht der Roboter?
  content_question_en: What does the robot look for?
  description_de: ''
  description_en: ''
  duration: 145
  name_de: Wire Cutters
  name_en: Wire Cutters
  src_id: WireCutters
